--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/J0k3rrWild/ChatAdminTools
build-by-default: true
branches:
- master
- api4
projects:
  ChatAdminTools:
    path: ""
    icon: "icon.png"
...
