---
name: ChatAdminTools
version: 1.1.0
main: J0k3rrWild\ChatAdminTools\Main
api: 4.0.3
website: https://github.com/J0k3rrWild
author: J0k3rrWild
permissions:
 chatadmintools:
  default: op
  description: Gives permission to all chat administration commands
 chatadmintools.bypass:
  default: op
  description: gives the permission to bypass the chat lock
 chatadmintools.clear:
  default: op
  description: Gives permission to clean the chat 
 chatadmintools.change:
  default: op
  description: Gives permission to disable / enable chat
       
...
