---
name: ChatAdminTools
version: 1.1.0
main: J0k3rrWild\ChatAdminTools\Main
api: 3.25.1
website: https://github.com/J0k3rrWild
author: J0k3rrWild
commands:
 ca:
  description: Chat administrative command
  permission: chatadmintools.command.chatadmintools
  usage: /ca clear <reason>* | on/off
  aliases: [chatadmintools, chatadmin]
permissions:
 chatadmintools:
  default: op
  description: Gives permission to all chat administration commands
 chatadmintools.bypass:
  default: op
  description: gives the permission to bypass the chat lock
 chatadmintools.clear:
  default: op
  description: Gives permission to clean the chat 
 chatadmintools.change:
  default: op
  description: Gives permission to disable / enable chat
...
