---
name: ChatAdminTools
version: 1.1.0
main: J0k3rrWild\ChatAdminTools\Main
api: 4.0.3
website: https://github.com/J0k3rrWild
author: J0k3rrWild
permissions:
 chatadmintools:
  default: op
  description: Daje uprawnienia do wszystkich komend administracyjncych chatu
 chatadmintools.bypass:
  default: op
  description: Daje uprawnienie omijania blokady chatu
 chatadmintools.clear:
  default: op
  description: Daje uprawnienie czyszczenia chatu 
 chatadmintools.change:
  default: op
  description: Daje uprawnienia wyłączenia/włączenia chatu
       
...
